### ISSUE TITLE
NameError: name 'Matrix' is not defined

### ISSUE THREAD

**Issue by ken2709** [daedalus/BreakingECDSAwithLLL#21]
Hello.
I have error below on python3.10, what i can do? Thanks.

C:\Users\K\Desktop\BreakingECDSAwithLLL-master>python crack_weak_ECDSA_nonces_with_LLL.py nonces.csv 176 6 grep -e e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Using: 6 sigs...
Traceback (most recent call last):
  File "C:\Users\K\Desktop\BreakingECDSAwithLLL-master\crack_weak_ECDSA_nonces_with_LLL.py", line 109, in <module>
    main()
  File "C:\Users\K\Desktop\BreakingECDSAwithLLL-master\crack_weak_ECDSA_nonces_with_LLL.py", line 97, in main
    matrix = make_matrix(msgs, sigs, pubs, B)
  File "C:\Users\K\Desktop\BreakingECDSAwithLLL-master\crack_weak_ECDSA_nonces_with_LLL.py", line 43, in make_matrix
    matrix = Matrix(QQ, m + 2, m + 2)
NameError: name 'Matrix' is not defined. Did you mean: 'matrix'?

**Comment by daedalus** [comment]
In my system works like a charm, i think you may have a problem with yours.
Try reinstalling sagemath.
Matrix is defined in the sage import, it should be there.
Nothing to do from my side.
